/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.poliedro.telainicioprofessor.telas;

import br.poliedro.telainicioprofessor.modelo.Usuario;
import br.poliedro.telainicioprofessor.persistencia.UsuarioDAO;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Lorenzo
 */
public class CadastroUsuarioTela extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroUsuarioTela
     */
    SucessoCadastroUsuarioTela scut = new SucessoCadastroUsuarioTela();
    ErroCadastroUsuarioTela ecut = new ErroCadastroUsuarioTela();
    
    public CadastroUsuarioTela() {
        initComponents();
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null); //retirar o painel superior
        pack();
        jDesktopPane1.add(scut);
        jDesktopPane1.add(ecut);
    }

    public static void centralizarInternalFrame(JInternalFrame internalFrame, JDesktopPane desktopPane) {
        int width = desktopPane.getWidth();
        int height = desktopPane.getHeight();
        int internalWidth = internalFrame.getWidth();
        int internalHeight = internalFrame.getHeight();

        internalFrame.setLocation(
                (width - internalWidth) / 2,
                (height - internalHeight) / 2
        );
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        serieLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        senhaTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        serieComboBox = new javax.swing.JComboBox<>();
        cadastrarButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        alunoComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(163, 236, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(450, 304));

        serieLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        serieLabel.setText("Série:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Email:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Senha:");

        nomeTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        emailTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        senhaTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        senhaTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-icon.png"))); // NOI18N
        jButton2.setText("Voltar");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        serieComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        serieComboBox.setMaximumRowCount(8);
        serieComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "6º ano", "7º ano", "8º ano", "9º ano" }));
        serieComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serieComboBox.setFocusable(false);
        serieComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serieComboBoxMouseClicked(evt);
            }
        });
        serieComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serieComboBoxActionPerformed(evt);
            }
        });

        cadastrarButton.setBackground(new java.awt.Color(204, 255, 255));
        cadastrarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cadastrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Adicionar.png"))); // NOI18N
        cadastrarButton.setText("Cadastrar");
        cadastrarButton.setBorder(null);
        cadastrarButton.setBorderPainted(false);
        cadastrarButton.setContentAreaFilled(false);
        cadastrarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarButton.setFocusPainted(false);
        cadastrarButton.setFocusable(false);
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });
        cadastrarButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastrarButtonKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel5.setText("Cadastro:");
        jLabel5.setFocusable(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("É aluno?");

        alunoComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alunoComboBox.setMaximumRowCount(2);
        alunoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        alunoComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alunoComboBox.setFocusable(false);
        alunoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(36, 36, 36)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(senhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(alunoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(serieLabel)))
                                    .addGap(18, 18, 18)
                                    .addComponent(serieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(senhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alunoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serieLabel)
                    .addComponent(serieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(cadastrarButton)
                .addGap(18, 18, 18))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 450, 322);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void serieComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serieComboBoxMouseClicked
        // TODO add your handling code here:
        if (serieComboBox.getSelectedItem().toString().equals("Selecione:")) {
            serieComboBox.removeItemAt(serieComboBox.getSelectedIndex());
            serieComboBox.setMaximumRowCount(7);
        }
    }//GEN-LAST:event_serieComboBoxMouseClicked

    private void serieComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serieComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serieComboBoxActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        // TODO add your handling code here:
        if ((nomeTextField.getText().length() >= 3 && emailTextField.getText().length() > 9 && senhaTextField.getText().length() > 4 && !serieComboBox.getSelectedItem().toString().equals("Selecione:")) || nomeTextField.getText().length() >= 3 && emailTextField.getText().length() > 9 && senhaTextField.getText().length() > 4 && serieComboBox.isVisible()== false) {
            var nome = nomeTextField.getText();
            var nomeCapitalizado = Character.toUpperCase(nome.charAt(0)) + nome.substring(1).toLowerCase(); // coloca a primeira letra do nome em maiúsculo em concatena com o resto
            var email = emailTextField.getText().toLowerCase(); // manda o email em minusculo
            var senha = senhaTextField.getText();
            var serie = serieComboBox.getSelectedItem().toString();

            Usuario u;

            if(alunoComboBox.getSelectedItem().toString().equals("Sim")){
                u = new Usuario(nomeCapitalizado, email, senha, serie);
            } else{
                u = new Usuario(nomeCapitalizado, email, senha);
            }

            try {
                var dao = new UsuarioDAO();
                if (alunoComboBox.getSelectedItem().toString().equals("Sim")) {
                    dao.cadastrar(u, false);
                } else {
                    dao.cadastrar(u, true);
                }
                SucessoCadastroUsuarioTela.centralizarInternalFrame(scut, jDesktopPane1);
                if (!scut.isVisible()) {
                    if(alunoComboBox.getSelectedItem().toString().equals("Sim")){
                        scut.mudarLabelAluno(nomeCapitalizado, serie);
                    } else{
                        scut.mudarLabelProfessor(nomeCapitalizado);
                    }
                    scut.setVisible(true);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else{
            ErroCadastroUsuarioTela.centralizarInternalFrame(ecut, jDesktopPane1);
            if(!ecut.isVisible()) {
                ecut.setVisible(true);
            }
        }
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void cadastrarButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastrarButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarButtonKeyPressed

    private void alunoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoComboBoxActionPerformed
        // TODO add your handling code here:
        if(serieComboBox.isVisible() && serieLabel.isVisible()){
            if(alunoComboBox.getSelectedItem().toString().equals("Não")){
                serieLabel.setVisible(false);
                serieComboBox.setVisible(false);
            }
        } else{
            if(alunoComboBox.getSelectedItem().toString().equals("Sim")){
                serieLabel.setVisible(true);
                serieComboBox.setVisible(true);
            }
        }

    }//GEN-LAST:event_alunoComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> alunoComboBox;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JTextField senhaTextField;
    private javax.swing.JComboBox<String> serieComboBox;
    private javax.swing.JLabel serieLabel;
    // End of variables declaration//GEN-END:variables
}
