/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.poliedro.telainicioprofessor.telas;

import java.awt.Component;
import java.beans.PropertyVetoException;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;

/**
 *
 * @author caiquef
 */
public class InicioTela extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicio
     */
    CadastroPerguntaTela cpt = new CadastroPerguntaTela(this);
    ConfiguracoesTela ct = new ConfiguracoesTela(this);
    CadastroUsuarioTela cut = new CadastroUsuarioTela();

    public InicioTela() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        jDesktopPane1.add(cpt);
        jDesktopPane1.add(ct);
        jDesktopPane1.add(cut);
    }

    public void adicionarNoDesktop(Component component) {
        if (component == null || jDesktopPane1 == null) {
            return;
        }

        try {
            // Remove se já existir
            if (component.getParent() == jDesktopPane1) {
                jDesktopPane1.remove(component);
            }

            // Adiciona o componente
            jDesktopPane1.add(component, JLayeredPane.DEFAULT_LAYER);
            component.setVisible(true);

            // Centraliza
            centerComponent(component);

            // Comportamentos específicos para JInternalFrame
            if (component instanceof JInternalFrame) {
                handleInternalFrame((JInternalFrame) component);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void centerComponent(Component component) {
        component.setLocation(
                (jDesktopPane1.getWidth() - component.getWidth()) / 2,
                (jDesktopPane1.getHeight() - component.getHeight()) / 2
        );
    }

    private void handleInternalFrame(JInternalFrame frame) throws PropertyVetoException {
        frame.setSelected(true);
        frame.moveToFront();
        frame.toFront();
        frame.setMaximum(false); // Garante que não está maximizado
    }

    public JDesktopPane getDesktop() {
        return jDesktopPane1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        rankingButton = new javax.swing.JButton();
        editarPerguntaButton = new javax.swing.JButton();
        cadastrarAlunoButton = new javax.swing.JButton();
        criarPerguntaButton = new javax.swing.JButton();
        inicioTextField = new javax.swing.JLabel();
        icone1Label = new javax.swing.JLabel();
        icone4Label = new javax.swing.JLabel();
        icone2Label = new javax.swing.JLabel();
        icone3Label = new javax.swing.JLabel();
        configButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2440, 1920));
        setMinimumSize(new java.awt.Dimension(1320, 720));
        setUndecorated(true);

        jDesktopPane1.setBackground(new java.awt.Color(163, 236, 255));

        jPanel2.setBackground(new java.awt.Color(163, 236, 255));

        jPanel1.setBackground(new java.awt.Color(163, 236, 255));

        rankingButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rankingButton.setText("Ranking");
        rankingButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        rankingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rankingButton.setFocusPainted(false);
        rankingButton.setFocusable(false);
        rankingButton.setOpaque(true);

        editarPerguntaButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editarPerguntaButton.setText("Editar pergunta");
        editarPerguntaButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        editarPerguntaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editarPerguntaButton.setFocusPainted(false);
        editarPerguntaButton.setFocusable(false);
        editarPerguntaButton.setOpaque(true);
        editarPerguntaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPerguntaButtonActionPerformed(evt);
            }
        });

        cadastrarAlunoButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cadastrarAlunoButton.setText("Cadastrar aluno");
        cadastrarAlunoButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cadastrarAlunoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cadastrarAlunoButton.setFocusPainted(false);
        cadastrarAlunoButton.setFocusable(false);
        cadastrarAlunoButton.setOpaque(true);
        cadastrarAlunoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarAlunoButtonActionPerformed(evt);
            }
        });

        criarPerguntaButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        criarPerguntaButton.setText("Criar pergunta");
        criarPerguntaButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        criarPerguntaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        criarPerguntaButton.setFocusPainted(false);
        criarPerguntaButton.setFocusable(false);
        criarPerguntaButton.setOpaque(true);
        criarPerguntaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarPerguntaButtonActionPerformed(evt);
            }
        });

        inicioTextField.setBackground(new java.awt.Color(51, 51, 51));
        inicioTextField.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        inicioTextField.setForeground(new java.awt.Color(255, 255, 255));
        inicioTextField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicioTextField.setText("INICIO");
        inicioTextField.setOpaque(true);

        icone1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AdicionarPergunta.png"))); // NOI18N

        icone4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Adicionar.png"))); // NOI18N

        icone2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EditarPergunta.png"))); // NOI18N

        icone3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ranking.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inicioTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(icone2Label)
                            .addComponent(icone1Label)
                            .addComponent(icone4Label)
                            .addComponent(icone3Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(criarPerguntaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editarPerguntaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rankingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadastrarAlunoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inicioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(criarPerguntaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(icone1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(icone2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editarPerguntaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rankingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icone3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastrarAlunoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icone4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        configButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Config.png"))); // NOI18N
        configButton.setBorderPainted(false);
        configButton.setContentAreaFilled(false);
        configButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        configButton.setFocusPainted(false);
        configButton.setFocusable(false);
        configButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(557, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(configButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(550, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(configButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void configButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configButtonActionPerformed
        // TODO add your handling code here:
        if (!ct.isVisible()) {
            ConfiguracoesTela.centralizarInternalFrame(ct, jDesktopPane1);
            ct.setVisible(true);
        }
    }//GEN-LAST:event_configButtonActionPerformed

    private void criarPerguntaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarPerguntaButtonActionPerformed
        // TODO add your handling code here:

        if (!cpt.isVisible()) {
            CadastroPerguntaTela.centralizarInternalFrame(cpt, jDesktopPane1);
            cpt.setVisible(true);
        }

    }//GEN-LAST:event_criarPerguntaButtonActionPerformed

    private void cadastrarAlunoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAlunoButtonActionPerformed
        // TODO add your handling code here:

        if (!cut.isVisible()) {
            CadastroUsuarioTela.centralizarInternalFrame(cut, jDesktopPane1);
            cut.setVisible(true);
        }
    }//GEN-LAST:event_cadastrarAlunoButtonActionPerformed

    private void editarPerguntaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPerguntaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarPerguntaButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarAlunoButton;
    private javax.swing.JButton configButton;
    private javax.swing.JButton criarPerguntaButton;
    private javax.swing.JButton editarPerguntaButton;
    private javax.swing.JLabel icone1Label;
    private javax.swing.JLabel icone2Label;
    private javax.swing.JLabel icone3Label;
    private javax.swing.JLabel icone4Label;
    private javax.swing.JLabel inicioTextField;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton rankingButton;
    // End of variables declaration//GEN-END:variables
}
