        package br.poliedro.telainicioprofessor.telas;

import br.poliedro.telainicioprofessor.modelo.Materia;
import br.poliedro.telainicioprofessor.modelo.PerguntaResposta;
import br.poliedro.telainicioprofessor.modelo.Perguntas;
import br.poliedro.telainicioprofessor.modelo.Respostas;
import br.poliedro.telainicioprofessor.persistencia.PerguntasMediaDAO;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;import java.awt.Container;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.Timer;


public class TelaPerguntaProfessor extends javax.swing.JInternalFrame {

    private Materia materiaSelecionada;
    private String dificuldade;
    
    public TelaPerguntaProfessor(Materia materia, String dificuldade) {
        initComponents();
        this.materiaSelecionada = materia;
    System.out.println("Matéria recebida na tela: " + materia.getNome());
    System.out.println("ID da matéria: " + materia.getId());
    this.dificuldade = dificuldade;    
    grupoBotoes.add(rbResposta1);
    grupoBotoes.add(rbResposta2);
    grupoBotoes.add(rbResposta3);
    grupoBotoes.add(rbResposta4);
    grupoBotoes.add(rbResposta5);
        // Configurações básicas
        setBorder(null);
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);

        // Timer para ajuste progressivo
        Timer timer = new Timer(50, e -> {
            Container parent = getParent();
            if (parent != null) {
                setSize(parent.getSize());
                setLocation(0, 0);
                tlPergunta.setSize(getSize());
                ((Timer) e.getSource()).stop();
            }
        });
        timer.start();
    }

    public CadastroPerguntaTela cadastroTela;

    public static void centralizarInternalFrame(JInternalFrame internalFrame, JDesktopPane desktopPane) {
        int width = desktopPane.getWidth();
        int height = desktopPane.getHeight();
        int internalWidth = internalFrame.getWidth();
        int internalHeight = internalFrame.getHeight();

        internalFrame.setLocation(
                (width - internalWidth) / 2,
                (height - internalHeight) / 2
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotoes = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        tlPergunta = new javax.swing.JPanel();
        btVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPergunta = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        txtResposta5 = new javax.swing.JTextField();
        txtResposta4 = new javax.swing.JTextField();
        txtResposta2 = new javax.swing.JTextField();
        txtResposta1 = new javax.swing.JTextField();
        txtResposta3 = new javax.swing.JTextField();
        rbResposta1 = new javax.swing.JRadioButton();
        rbResposta2 = new javax.swing.JRadioButton();
        rbResposta3 = new javax.swing.JRadioButton();
        rbResposta4 = new javax.swing.JRadioButton();
        rbResposta5 = new javax.swing.JRadioButton();
        btSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);

        tlPergunta.setBackground(new java.awt.Color(163, 236, 255));
        tlPergunta.setMaximumSize(new java.awt.Dimension(2440, 1920));
        tlPergunta.setMinimumSize(new java.awt.Dimension(1320, 720));

        btVoltar.setBackground(new java.awt.Color(163, 236, 255));
        btVoltar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-icon.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setBorder(null);
        btVoltar.setBorderPainted(false);
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btVoltar.setFocusPainted(false);
        btVoltar.setFocusable(false);
        btVoltar.setRolloverEnabled(false);
        btVoltar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                btVoltarAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        txtPergunta.setBackground(new java.awt.Color(204, 204, 204));
        txtPergunta.setColumns(20);
        txtPergunta.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtPergunta.setLineWrap(true);
        txtPergunta.setRows(5);
        txtPergunta.setText("Insira a pergunta aqui:");
        txtPergunta.setWrapStyleWord(true);
        txtPergunta.setFocusable(false);
        txtPergunta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPerguntaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtPergunta);

        jPanel2.setBackground(new java.awt.Color(163, 236, 255));

        txtResposta5.setBackground(new java.awt.Color(255, 51, 51));
        txtResposta5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtResposta5.setText("Resposta 5");
        txtResposta5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtResposta5MouseClicked(evt);
            }
        });
        txtResposta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResposta5ActionPerformed(evt);
            }
        });
        txtResposta5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtResposta5KeyPressed(evt);
            }
        });

        txtResposta4.setBackground(new java.awt.Color(255, 153, 0));
        txtResposta4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtResposta4.setText("Resposta 4");
        txtResposta4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtResposta4MouseClicked(evt);
            }
        });
        txtResposta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResposta4ActionPerformed(evt);
            }
        });

        txtResposta2.setBackground(new java.awt.Color(255, 204, 51));
        txtResposta2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtResposta2.setText("Resposta 2");
        txtResposta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtResposta2MouseClicked(evt);
            }
        });
        txtResposta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResposta2ActionPerformed(evt);
            }
        });

        txtResposta1.setBackground(new java.awt.Color(102, 255, 255));
        txtResposta1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtResposta1.setText("Resposta 1");
        txtResposta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtResposta1MouseClicked(evt);
            }
        });
        txtResposta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResposta1ActionPerformed(evt);
            }
        });

        txtResposta3.setBackground(new java.awt.Color(51, 255, 51));
        txtResposta3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtResposta3.setText("Resposta 3");
        txtResposta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtResposta3MouseClicked(evt);
            }
        });
        txtResposta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResposta3ActionPerformed(evt);
            }
        });

        rbResposta1.setBackground(new java.awt.Color(163, 236, 255));
        rbResposta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbResposta1ActionPerformed(evt);
            }
        });

        rbResposta2.setBackground(new java.awt.Color(163, 236, 255));

        rbResposta3.setBackground(new java.awt.Color(163, 236, 255));

        rbResposta4.setBackground(new java.awt.Color(163, 236, 255));

        rbResposta5.setBackground(new java.awt.Color(163, 236, 255));

        btSalvar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSalvar.setFocusable(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbResposta5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtResposta5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbResposta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtResposta1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbResposta2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtResposta2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbResposta3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtResposta3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbResposta4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtResposta4))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(btSalvar)
                .addGap(0, 264, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtResposta1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbResposta1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtResposta2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(rbResposta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtResposta3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(rbResposta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtResposta4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbResposta4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbResposta5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(90, 90, 90))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtResposta5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSalvar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Marque a caixa da resposta correta!");

        javax.swing.GroupLayout tlPerguntaLayout = new javax.swing.GroupLayout(tlPergunta);
        tlPergunta.setLayout(tlPerguntaLayout);
        tlPerguntaLayout.setHorizontalGroup(
            tlPerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tlPerguntaLayout.createSequentialGroup()
                .addGap(0, 336, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(342, Short.MAX_VALUE))
            .addGroup(tlPerguntaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tlPerguntaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tlPerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tlPerguntaLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tlPerguntaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        tlPerguntaLayout.setVerticalGroup(
            tlPerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tlPerguntaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(tlPergunta, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tlPergunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(tlPergunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btVoltarAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btVoltarAncestorMoved

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        System.out.println("Matéria na hora de salvar: " + materiaSelecionada);
        if (materiaSelecionada != null) {
            System.out.println("Nome: " + materiaSelecionada.getNome());
            System.out.println("ID: " + materiaSelecionada.getId());
        } else {
            System.out.println("A matéria está null!");
        }

        String enunciado = txtPergunta.getText().trim();
        String resposta1 = txtResposta1.getText().trim();
        String resposta2 = txtResposta2.getText().trim();
        String resposta3 = txtResposta3.getText().trim();
        String resposta4 = txtResposta4.getText().trim();
        String resposta5 = txtResposta5.getText().trim();

        boolean correta1 = rbResposta1.isSelected();
        boolean correta2 = rbResposta2.isSelected();
        boolean correta3 = rbResposta3.isSelected();
        boolean correta4 = rbResposta4.isSelected();
        boolean correta5 = rbResposta5.isSelected();

        if (materiaSelecionada == null) {
            JOptionPane.showMessageDialog(this, "Matéria selecionada inválida!");
            return;
        }
        if (enunciado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, insira a pergunta.");
            return;
        }
        if (resposta1.isEmpty() || resposta2.isEmpty() || resposta3.isEmpty() || resposta4.isEmpty() || resposta5.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todas as respostas.");
            return;
        }

        int totalCorretas = 0;
        totalCorretas += correta1 ? 1 : 0;
        totalCorretas += correta2 ? 1 : 0;
        totalCorretas += correta3 ? 1 : 0;
        totalCorretas += correta4 ? 1 : 0;
        totalCorretas += correta5 ? 1 : 0;

        if (totalCorretas != 1) {
            JOptionPane.showMessageDialog(this, "Por favor, marque exatamente uma resposta correta.");
            return;
        }

        Perguntas pergunta = new Perguntas(enunciado);
        pergunta.setDificuldade(dificuldade);
        pergunta.setIdMateria(materiaSelecionada.getId());

        pergunta.getRespostas().add(new PerguntaResposta(pergunta, new Respostas(resposta1), correta1));
        pergunta.getRespostas().add(new PerguntaResposta(pergunta, new Respostas(resposta2), correta2));
        pergunta.getRespostas().add(new PerguntaResposta(pergunta, new Respostas(resposta3), correta3));
        pergunta.getRespostas().add(new PerguntaResposta(pergunta, new Respostas(resposta4), correta4));
        pergunta.getRespostas().add(new PerguntaResposta(pergunta, new Respostas(resposta5), correta5));

        try {
            PerguntasMediaDAO dao = new PerguntasMediaDAO();
            dao.cadastrarPergunta(pergunta);
            JOptionPane.showMessageDialog(this, "Pergunta cadastrada com sucesso!");
            // Opcional: limpar campos após salvar
            limparCampos();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar pergunta: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btSalvarActionPerformed
    private void limparCampos() {
        txtPergunta.setText("Insira a Pergunta:");
        txtResposta1.setText("Resposta 1");
        txtResposta2.setText("Resposta 2");
        txtResposta3.setText("Resposta 3");
        txtResposta4.setText("Resposta 4");
        txtResposta5.setText("Resposta 5");
        grupoBotoes.clearSelection();
    }
    
    private void txtPerguntaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPerguntaMouseClicked
        // TODO add your handling code here:
        txtPergunta.setFocusable(true);
        txtPergunta.setText("");
    }//GEN-LAST:event_txtPerguntaMouseClicked

    private void txtResposta5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResposta5MouseClicked
        // TODO add your handling code here:
        txtResposta5.setText("");
    }//GEN-LAST:event_txtResposta5MouseClicked

    private void txtResposta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResposta5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResposta5ActionPerformed

    private void txtResposta5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResposta5KeyPressed

    }//GEN-LAST:event_txtResposta5KeyPressed

    private void txtResposta4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResposta4MouseClicked
        // TODO add your handling code here:
        txtResposta4.setText("");
    }//GEN-LAST:event_txtResposta4MouseClicked

    private void txtResposta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResposta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResposta4ActionPerformed

    private void txtResposta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResposta2MouseClicked
        // TODO add your handling code here:
        txtResposta2.setText("");
    }//GEN-LAST:event_txtResposta2MouseClicked

    private void txtResposta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResposta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResposta2ActionPerformed

    private void txtResposta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResposta1MouseClicked
        // TODO add your handling code here:
        txtResposta1.setText("");
    }//GEN-LAST:event_txtResposta1MouseClicked

    private void txtResposta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResposta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResposta1ActionPerformed

    private void txtResposta3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResposta3MouseClicked
        // TODO add your handling code here:
        txtResposta3.setText("");
    }//GEN-LAST:event_txtResposta3MouseClicked

    private void txtResposta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResposta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResposta3ActionPerformed

    private void rbResposta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbResposta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbResposta1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.ButtonGroup grupoBotoes;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbResposta1;
    private javax.swing.JRadioButton rbResposta2;
    private javax.swing.JRadioButton rbResposta3;
    private javax.swing.JRadioButton rbResposta4;
    private javax.swing.JRadioButton rbResposta5;
    private javax.swing.JPanel tlPergunta;
    private javax.swing.JTextArea txtPergunta;
    private javax.swing.JTextField txtResposta1;
    private javax.swing.JTextField txtResposta2;
    private javax.swing.JTextField txtResposta3;
    private javax.swing.JTextField txtResposta4;
    private javax.swing.JTextField txtResposta5;
    // End of variables declaration//GEN-END:variables
}
