CREATE DATABASE logins;
USE logins;

CREATE TABLE login_professor ( id_professor INTEGER PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(50) NOT NULL,
senha VARCHAR (50) NOT NULL);

CREATE TABLE login_aluno ( id_aluno INTEGER PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(50) NOT NULL,
senha VARCHAR(50) NOT NULL,
RA CHAR(6) NULL);


