/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

/**
 *
 * @author diego
 */
public class TelaMaterias extends javax.swing.JFrame {

    /**
     * Creates new form TelaMaterias
     */
    public TelaMaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotãoPort = new javax.swing.JButton();
        BotãoMat = new javax.swing.JButton();
        BotãoCien = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BotãoVol = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BotãoHist = new javax.swing.JButton();
        BotãoGeo = new javax.swing.JButton();
        BotãoFis = new javax.swing.JButton();
        BotãoBio = new javax.swing.JButton();
        BotãoQui = new javax.swing.JButton();
        BotãoFilo = new javax.swing.JButton();
        BotãoSocio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PanelMoedas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 768));

        BotãoPort.setBackground(new java.awt.Color(0, 153, 153));
        BotãoPort.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BotãoPort.setForeground(new java.awt.Color(255, 255, 255));
        BotãoPort.setText("Português");
        BotãoPort.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotãoPort.setPreferredSize(new java.awt.Dimension(72, 23));
        BotãoPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoPortActionPerformed(evt);
            }
        });

        BotãoMat.setBackground(new java.awt.Color(0, 153, 153));
        BotãoMat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BotãoMat.setForeground(new java.awt.Color(255, 255, 255));
        BotãoMat.setText("Matemática");
        BotãoMat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotãoMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoMatActionPerformed(evt);
            }
        });

        BotãoCien.setBackground(new java.awt.Color(0, 153, 153));
        BotãoCien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BotãoCien.setForeground(new java.awt.Color(255, 255, 255));
        BotãoCien.setText("Ciências");
        BotãoCien.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotãoCien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoCienActionPerformed(evt);
            }
        });

        BotãoVol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seta-removebg-esquerda.png"))); // NOI18N
        BotãoVol.setText("Voltar");
        BotãoVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoVolActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(210, 75));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MATÉRIAS");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        BotãoHist.setBackground(new java.awt.Color(0, 153, 153));
        BotãoHist.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BotãoHist.setForeground(new java.awt.Color(255, 255, 255));
        BotãoHist.setText("História");
        BotãoHist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotãoHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoHistActionPerformed(evt);
            }
        });

        BotãoGeo.setBackground(new java.awt.Color(0, 153, 153));
        BotãoGeo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BotãoGeo.setForeground(new java.awt.Color(255, 255, 255));
        BotãoGeo.setText("Geografia");
        BotãoGeo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotãoGeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoGeoActionPerformed(evt);
            }
        });

        BotãoFis.setBackground(new java.awt.Color(0, 153, 153));
        BotãoFis.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BotãoFis.setForeground(new java.awt.Color(255, 255, 255));
        BotãoFis.setText("Física");
        BotãoFis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotãoFis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoFisActionPerformed(evt);
            }
        });

        BotãoBio.setBackground(new java.awt.Color(0, 153, 153));
        BotãoBio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BotãoBio.setForeground(new java.awt.Color(255, 255, 255));
        BotãoBio.setText("Biologia");
        BotãoBio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotãoBio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoBioActionPerformed(evt);
            }
        });

        BotãoQui.setBackground(new java.awt.Color(0, 153, 153));
        BotãoQui.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BotãoQui.setForeground(new java.awt.Color(255, 255, 255));
        BotãoQui.setText("Química");
        BotãoQui.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotãoQui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoQuiActionPerformed(evt);
            }
        });

        BotãoFilo.setBackground(new java.awt.Color(0, 153, 153));
        BotãoFilo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BotãoFilo.setForeground(new java.awt.Color(255, 255, 255));
        BotãoFilo.setText("Filosofia");
        BotãoFilo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotãoFilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoFiloActionPerformed(evt);
            }
        });

        BotãoSocio.setBackground(new java.awt.Color(0, 153, 153));
        BotãoSocio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BotãoSocio.setForeground(new java.awt.Color(255, 255, 255));
        BotãoSocio.setText("Sociologia");
        BotãoSocio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotãoSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoSocioActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/POLIEDROMOEDA-removebg-preview.png"))); // NOI18N

        PanelMoedas.setBackground(new java.awt.Color(255, 255, 255));
        PanelMoedas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel4.setText("Moedas Totais: 0");

        javax.swing.GroupLayout PanelMoedasLayout = new javax.swing.GroupLayout(PanelMoedas);
        PanelMoedas.setLayout(PanelMoedasLayout);
        PanelMoedasLayout.setHorizontalGroup(
            PanelMoedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMoedasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        PanelMoedasLayout.setVerticalGroup(
            PanelMoedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMoedasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoPoliedroAMIlhao-removebg-300png.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(PanelMoedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(869, 869, 869)
                .addComponent(jLabel5))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1354, 1354, 1354)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(BotãoCien, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(BotãoQui, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(BotãoGeo, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(BotãoFilo, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(BotãoHist, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(BotãoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(637, 637, 637)
                .addComponent(BotãoVol))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotãoPort, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotãoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(202, 202, 202)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotãoBio, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotãoFis, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(621, 621, 621)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(PanelMoedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotãoPort, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotãoFis, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotãoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(BotãoBio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotãoCien, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotãoQui, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotãoGeo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotãoFilo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotãoHist, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotãoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(BotãoVol))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotãoVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoVolActionPerformed
        // TODO add your handling code here:
        TelaModos telaInicial = new TelaModos();
        telaInicial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotãoVolActionPerformed

    private void BotãoPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoPortActionPerformed
        // TODO add your handling code here:
        TelaJogo telaJogo = new TelaJogo();
        telaJogo.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BotãoPortActionPerformed

    private void BotãoCienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoCienActionPerformed
            // TODO add your handling code here:
        TelaJogo telaJogo = new TelaJogo();
        telaJogo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotãoCienActionPerformed

    private void BotãoMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoMatActionPerformed
        // TODO add your handling code here:
        TelaJogo telaJogo = new TelaJogo();
        telaJogo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotãoMatActionPerformed

    private void BotãoHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoHistActionPerformed
        // TODO add your handling code here:
        TelaJogo telaJogo = new TelaJogo();
        telaJogo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotãoHistActionPerformed

    private void BotãoGeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoGeoActionPerformed
        // TODO add your handling code here:
        TelaJogo telaJogo = new TelaJogo();
        telaJogo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotãoGeoActionPerformed

    private void BotãoFisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoFisActionPerformed
        // TODO add your handling code here:
        TelaJogo telaJogo = new TelaJogo();
        telaJogo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotãoFisActionPerformed

    private void BotãoBioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoBioActionPerformed
        // TODO add your handling code here:
        TelaJogo telaJogo = new TelaJogo();
        telaJogo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotãoBioActionPerformed

    private void BotãoQuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoQuiActionPerformed
        // TODO add your handling code here:
        TelaJogo telaJogo = new TelaJogo();
        telaJogo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotãoQuiActionPerformed

    private void BotãoFiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoFiloActionPerformed
        // TODO add your handling code here:
        TelaJogo telaJogo = new TelaJogo();
        telaJogo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotãoFiloActionPerformed

    private void BotãoSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoSocioActionPerformed
        // TODO add your handling code here:
        TelaJogo telaJogo = new TelaJogo();
        telaJogo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotãoSocioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMaterias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotãoBio;
    private javax.swing.JButton BotãoCien;
    private javax.swing.JButton BotãoFilo;
    private javax.swing.JButton BotãoFis;
    private javax.swing.JButton BotãoGeo;
    private javax.swing.JButton BotãoHist;
    private javax.swing.JButton BotãoMat;
    private javax.swing.JButton BotãoPort;
    private javax.swing.JButton BotãoQui;
    private javax.swing.JButton BotãoSocio;
    private javax.swing.JButton BotãoVol;
    private javax.swing.JPanel PanelMoedas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
