/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.TelaAluno.telas;

/**
 *
 * @author diego
 */
public class pularajudaTela extends javax.swing.JFrame {
    public TelaJogo telaJogo;
  
    /**
     * Creates new form pularTela
     */
    public pularajudaTela(TelaJogo telaJogo) {
        initComponents();
        this.telaJogo = telaJogo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        simBotao = new javax.swing.JButton();
        naoBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        fundoPanel.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Deseja pular para próxima pergunta?");

        simBotao.setBackground(new java.awt.Color(51, 204, 255));
        simBotao.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        simBotao.setForeground(new java.awt.Color(255, 255, 255));
        simBotao.setText("Sim");
        simBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simBotaoActionPerformed(evt);
            }
        });

        naoBotao.setBackground(new java.awt.Color(51, 204, 255));
        naoBotao.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        naoBotao.setForeground(new java.awt.Color(255, 255, 255));
        naoBotao.setText("Não");
        naoBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fundoPanelLayout = new javax.swing.GroupLayout(fundoPanel);
        fundoPanel.setLayout(fundoPanelLayout);
        fundoPanelLayout.setHorizontalGroup(
            fundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoPanelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(naoBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(88, 88, 88)
                .addComponent(simBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        fundoPanelLayout.setVerticalGroup(
            fundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(fundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(naoBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void simBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simBotaoActionPerformed
        // TODO add your handling code here:
        telaJogo.proximaPergunta();
        telaJogo.pararTemporizador();
        this.dispose();
        
    }//GEN-LAST:event_simBotaoActionPerformed

    private void naoBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoBotaoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_naoBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    TelaJogo tela = new TelaJogo();

    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new pularajudaTela(tela).setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fundoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton naoBotao;
    private javax.swing.JButton simBotao;
    // End of variables declaration//GEN-END:variables
}
